// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuiJcziUnIHxt5nsXLN4aBIc7HyYIjC8w',
    appId: '1:1080171621537:web:54c5017f78d365bb7f54e0',
    messagingSenderId: '1080171621537',
    projectId: 'project3-9c3d4',
    authDomain: 'project3-9c3d4.firebaseapp.com',
    storageBucket: 'project3-9c3d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBExDIISqQgLd3mcfqXb1VBXEAZ8kBOssI',
    appId: '1:1080171621537:android:892e658c87c482cf7f54e0',
    messagingSenderId: '1080171621537',
    projectId: 'project3-9c3d4',
    storageBucket: 'project3-9c3d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo2mWdW3eYCZ6gPQ64s-RvmsTea9tiHfs',
    appId: '1:1080171621537:ios:a4bc8218abeae9937f54e0',
    messagingSenderId: '1080171621537',
    projectId: 'project3-9c3d4',
    storageBucket: 'project3-9c3d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo2mWdW3eYCZ6gPQ64s-RvmsTea9tiHfs',
    appId: '1:1080171621537:ios:a4bc8218abeae9937f54e0',
    messagingSenderId: '1080171621537',
    projectId: 'project3-9c3d4',
    storageBucket: 'project3-9c3d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuiJcziUnIHxt5nsXLN4aBIc7HyYIjC8w',
    appId: '1:1080171621537:web:4fd1bf04734d8cd97f54e0',
    messagingSenderId: '1080171621537',
    projectId: 'project3-9c3d4',
    authDomain: 'project3-9c3d4.firebaseapp.com',
    storageBucket: 'project3-9c3d4.firebasestorage.app',
  );
}
